[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[theme]
primaryColor = "#065535"
backgroundColor = "#f6f8fa"
secondaryBackgroundColor = "#e8f0ec"
textColor = "#04322a"
font = "sans serif"

[browser]
gatherUsageStats = false
